pipeline {

    agent any

    tools {
        nodejs 'node20'
    }

    triggers {
        githubPush()
    }

    environment {

        IMAGE_NAME = "pawapay"
        IMAGE_TAG = "latest"

        DOCKER_USER = "dulcinee"

        KUBE_NAMESPACE = "jenkins"
        KUBE_CRED_ID = "k8s"

        SONAR_PROJECT = "ai-pipeline"

        GEMMA_URL = "http://192.168.100.46:11434"
    }


    stages {


        stage('Start Pipeline') {

            steps {

                script {

                    try {

                        mail(
                            body: 'Le pipeline automatique a commencé.',
                            subject: 'Pipeline Started',
                            to: 'dulcinemfo@gmail.com'
                        )

                    } catch(Exception e) {

                        echo "Erreur envoi mail démarrage"

                    }

                }

            }

        }



        stage('Checkout GitHub') {

            steps {

                git branch: 'main',
                    credentialsId: 'jenkis-github-mystoche',
                    url: 'https://github.com/Mystoche/pipeline-ai.git'

            }

        }



        stage('Install Dependencies') {

            steps {

                dir('pre-prod') {

                    sh '''
                    npm install
                    '''

                }

            }

        }



        stage('Code Tests') {

            steps {

                dir('pre-prod') {

                    echo "Execution des tests"

                    sh '''
                    npm test -- --coverage
                    '''

                }

            }

        }




        stage('Build TypeScript') {

            steps {

                dir('pre-prod') {

                    sh '''
                    npx tsc
                    '''

                }

            }

        }




        stage('SonarQube Analysis') {

            steps {

                script {


                    def scannerHome = tool 'SonarQube-Scanner'


                    withSonarQubeEnv('Sonarqube') {


                        dir('pre-prod') {


                            sh """

                            ${scannerHome}/bin/sonar-scanner \

                            -Dsonar.projectName=${SONAR_PROJECT} \

                            -Dsonar.projectKey=${SONAR_PROJECT} \

                            -Dsonar.sources=src \

                            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

                            """


                        }


                    }


                }

            }

        }





        stage('Quality Gate') {

            steps {


                timeout(time:5, unit:'MINUTES') {


                    waitForQualityGate abortPipeline:true


                }


            }

        }




        stage('AI Code Review - Gemma') {


            steps {


                script {


                    sh '''

                    echo "Analyse IA Gemma"



                    curl ${GEMMA_URL}/api/generate \

                    -H "Content-Type: application/json" \

                    -d '{

                    "model":"gemma3:4b",

                    "prompt":"Analyse ce projet TypeScript apres les tests et SonarQube. Donne les erreurs possibles et les recommandations.",

                    "stream":false

                    }' > ai-report.json



                    cat ai-report.json


                    '''


                }


            }


        }





        stage('Build Docker Image') {


            steps {


                dir('pre-prod') {


                    sh """

                    docker build \

                    -t ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_TAG} .

                    """


                }


            }


        }





        stage('Trivy Image Scan') {


            steps {


                script {


                    try {


                        sh """

                        docker exec trivy-scan \

                        trivy image \

                        --severity CRITICAL \

                        ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_TAG}

                        """



                    } catch(Exception e) {



                        mail(

                        body:'Vulnerabilites critiques detectees par Trivy.',

                        subject:'Trivy Scan FAILED',

                        to:'dulcinemfo@gmail.com'

                        )



                        error("Pipeline bloque par Trivy")

                    }


                }


            }


        }






        stage('Push Docker Image') {


            steps {



                withCredentials([

                    usernamePassword(

                        credentialsId:'docker',

                        usernameVariable:'DOCKER_USER_ID',

                        passwordVariable:'DOCKER_PASS'

                    )

                ]) {



                    sh '''

                    echo $DOCKER_PASS | docker login \

                    -u $DOCKER_USER_ID \

                    --password-stdin



                    docker push ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_TAG}


                    '''



                }


            }


        }






        stage('Deploy Kubernetes') {


            steps {


                withKubeConfig([

                    credentialsId:"${KUBE_CRED_ID}",

                    serverUrl:'https://192.168.49.2:8443'

                ]) {



                    sh """

                    kubectl apply \

                    -f manifeste/deployment.yaml \

                    -n ${KUBE_NAMESPACE} \

                    --validate=false

                    """



                }


            }


        }



    }




    post {


        success {


            mail(

            body:'Pipeline SUCCESS : Application deployee sur Kubernetes.',

            subject:'Pipeline Success',

            to:'dulcinemfo@gmail.com'

            )


        }



        failure {


            echo "Pipeline FAILED - voir les logs Jenkins"


        }



    }


}
